# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c22ed1b491f90f341f741bea0f989a092fa4624fc282804547b058459ad43cb76bf4e99889866eaff72d3f7908e03454d2b2ca6fc2e004ecab037335cc2a8c32

test:
  secret_key_base: a701864797f558ef1d6ed091e3a459ddc936f1696dbe1412430e4a7ceddc37a2c3693512b3773603f78bfaceb910f3de13a21fc589d78f9e0d62fa70c99ef51a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
